---
- import_playbook: gather-facts.yml

- name: Apply role baremetal
  hosts: baremetal
  serial: '{{ kolla_serial|default("0") }}'
  gather_facts: false
  roles:
    - { role: baremetal,
        tags: baremetal }
  environment:
    http_proxy: '{{ http_proxy | default("")}}'
    https_proxy: '{{ https_proxy | default("")}}'
    no_proxy: '{{ no_proxy | default("")}}'

